version: '2'
services:
    # webコンテナ
    web:
        image: nginx:latest
        # パスをボリュームとしてマウント {ホスト側:コンテナ側}
        volumes:
            - ./web:/usr/share/nginx/html
        ports:
            - 80

    # apiコンテナ
    api:
        build: ./api
        ports:
            - 80

    # リバースプロキシコンテナ
    proxy:
        build: ./proxy
        # リンク先コンテナに振り分けるコンテナを設定 {コンテナ名:エイリアス名}
        links:
            - web:web
            - api:api
        ports:
            - 80:80
        tty: true